version: '3'

services:
  db:
    container_name: strafeek-db
    image: postgres
    ports:
      - "5111:5432"
    environment:
      POSTGRES_DB: strafeek
      POSTGRES_USER: strafeek
      POSTGRES_PASSWORD: strafeek
    volumes:
      - "~/strafeek-db/postgres.conf:/usr/local/etc/postgres/postgres.conf"
      - "~/strafeek-db/data:/var/lib/postgresql/data:delegated"
    restart: unless-stopped
